# Generated by Django 3.2 on 2021-05-04 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomProvider',
            new_name='Provider',
        ),
    ]
